# Generated by Django 3.1.2 on 2020-10-17 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUser',
            fields=[
                ('telegram_username', models.CharField(max_length=1000, unique=True)),
                ('locuser_id', models.AutoField(primary_key=True, serialize=False)),
                ('enable', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('text_sent', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('locuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.locationuser')),
            ],
        ),
    ]
