# Generated by Django 3.1.2 on 2020-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationuser',
            name='text_sent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
