# Generated by Django 3.1.2 on 2020-10-17 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20201017_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationstream',
            name='last_update_time',
        ),
        migrations.AddField(
            model_name='locationstream',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 17, 15, 32, 44, 118271)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationstream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
